# Numpy 
- Numpy is a general purpose array processing package.
- It provides a high performance multidimensional package.
- Array is a data structure that stores the values of same data type.
- This is the main difference btwn LIST ansd ARRAY in python 

In [1]:
## Initially we need to import numpy
 
import numpy as np

In [2]:
lst=[1,2,3,4,4,5]
arr=np.array(lst)

In [3]:
type(arr)

numpy.ndarray

In [5]:
print(arr)   # here there is one square bracket that denotes single dimensional array

[1 2 3 4 4 5]


In [7]:
arr.size #number of ele in array

6

In [8]:
arr.shape #shape gives number of rows and columns in array

#for 1-D array we will get how many numbers are there using SHAPE 

(6,)

In [9]:
# using the same ele in the array we can reshape the array 

arr.reshape(2,3)

array([[1, 2, 3],
       [4, 4, 5]])

In [10]:
arr.reshape(3,2)   # here there are 2 square brackets means it is 2 dimensional array

array([[1, 2],
       [3, 4],
       [4, 5]])

In [4]:
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[9,10,11,12]

In [5]:
arr1=np.array([list1,list2,list3])

In [6]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
# check the shape of array
arr1.shape  

(3, 4)

In [7]:
arr1.size

12

In [23]:
# we can reshape array in the combination of 3*4=12 [(3,4),(4,3),(1,12),(12,1),(6,2),(2,6)]
arr2=arr1.reshape(1,12)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [25]:
# Indexing
# accessing ele in array

arr3=np.array([1,2,3,4,6,7,4,5])
arr3

array([1, 2, 3, 4, 6, 7, 4, 5])

In [26]:
arr3[0]

1

In [27]:
arr3*2 #multiplying all ele with 2

array([ 2,  4,  6,  8, 12, 14,  8, 10])

In [30]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
# accessing sub array from an array

arr1[:,:]
## syntax
##array[index of elements we need:untill which row we need(means actuall index of row-1)(rows),: index of elements we need:untill which col we need(means actuall index of col-1)(columns)]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
#suppose if we want retrive ele of 1,2,5,6 then
#coming to the row part [index of 1st row:untill which row we need]  similarly for col
arr1[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [35]:
#retrive 3,4,7,8,11,12

arr1[0:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [36]:
#retrive 6,7,10,11

arr1[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [37]:
#we can also create array in the below format

arr5=np.arange(1,11)

In [38]:
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# we can also arrange ele with gap of equal intervals

arr6=np.arange(1,10,3) # here gap between 1,4,7 is 3
arr6

array([1, 4, 7])

In [43]:
np.linspace(1,10,20)
#gives 20 numbers between 1 to 10 with equal intervals

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [44]:
#copy function and broadcasting

arr

array([1, 2, 3, 4, 4, 5])

In [45]:
arr[3:]=100 #from 3rd ele all ele are assigned with 100

In [46]:
arr

array([  1,   2,   3, 100, 100, 100])

In [47]:
arr7=arr 
#means we are assigning arr with arr7
#reference of assigning creates only single memory
arr7[3:]=500

In [48]:
arr7

array([  1,   2,   3, 500, 500, 500])

In [49]:
arr

array([  1,   2,   3, 500, 500, 500])

In [55]:
# here we not assigned arr to 500 but it has been changed 
#inorder to avoid this we move for COPY function

arr7=arr.copy()   #copy creates another memory 
arr7[3:]=1000
arr7


array([   1,    2,    3, 1000, 1000, 1000])

In [56]:
arr  
# see here even after copying arr and arr7 is different 
# this is because we used copy function

array([  1,   2,   3, 500, 500, 500])

In [57]:
## Some conditions very useful in Explority Data Analysis

val=2
arr<val #here in array each ele is verified if it is less than 2 or not

array([ True, False, False, False, False, False])

In [60]:
#If we want ele in the array which are less than 2
arr[arr<val]

array([1])

In [58]:
arr

array([  1,   2,   3, 500, 500, 500])

In [59]:
arr*2 # each ele is multiplied by 2

array([   2,    4,    6, 1000, 1000, 1000])

In [68]:
#create array and reshape
arr1=np.arange(0,10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
arr2=np.arange(11,21).reshape(2,5)
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [78]:
arr1*arr2

array([[  0,  12,  26,  42,  60],
       [ 80, 102, 126, 152, 180]])

In [79]:
np.ones(10) 
#prints array with 10 ele 
#by default it prints float values
#1-D array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
np.ones(10,dtype=int)
#print integer values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [82]:
np.ones((2,5),dtype=int)
#2-D array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [85]:
## random distribution
np.random.rand(3,3) 
#gives random values of 2-D array 3X3
#this output will vary for each execution as these are random values

array([[0.87171194, 0.23848478, 0.25932953],
       [0.72722293, 0.51237333, 0.47960795],
       [0.50049913, 0.70920563, 0.03345203]])

In [86]:
#standard normal distribution
np.random.randn(4,4)

array([[-0.915968  , -0.40250186, -0.96188701,  0.12093926],
       [ 0.41076218,  0.32397134, -0.56765033,  0.78973852],
       [-0.464112  ,  0.63529462, -1.05583511, -1.85671384],
       [ 0.51921069,  0.19310036, -0.84491878,  1.3407482 ]])

In [89]:
np.random.randint(0,30,10).reshape(2,5)

array([[19, 15,  0, 10, 20],
       [ 5, 22,  5,  0, 10]])

In [91]:
np.random.random_sample((1,5))

array([[0.80398244, 0.52454783, 0.55759132, 0.88903453, 0.83028188]])